spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-1.cx7pm8zlmjuv.ap-northeast-2.rds.amazonaws.com:3306/aha_point?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: admin
    password: uiop9900

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      show-sql: true
      defer-datasource-initialization: true # data.sql 실행을 위한 추가


  sql:
    init:
      mode: always  # data.sql 실행을 위한 추가

jwt:
  secret: ahaahaahaackjbskjvbdjkbvwvkndfkvjbsdljnbcvwoieh

message:
  api:
    key: NCSMDO6G14FAUDYE
    secret: TRRXJG5BFAJITU1LLHPVQWPHAD3LSQNH
  domain:
    address: https://api.coolsms.co.kr



