

spring:
  application:
    name: member
  thymeleaf:
    enabled: true
  aop:
    auto:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aha_point?serverTimezone=Asia/Seoul
    username: root
    password: uiop9900

# HTTP 2.0 ??
server:
  error:
    whitelabel:
      enabled: false # ????? ??
  http2:
    enabled: true
      # Enable or disable the introspection query. Disabling it puts your server in contravention of the GraphQL
      # specification and expectations of most clients, so use this option with caution

# http://localhost:8080/swagger-ui/index.html
springdoc:
  swagger-ui:
    enabled: true
    path: "swagger.html"
    tags-sorter: "alpha"
    operations-sorter: "alpha"
  packages-to-scan: "com.member"
  default-consumes-media-type: "application/json;charset=UTF-8"
  default-produces-media-type: "application/json;charset=UTF-8"
  api-docs:
    path: "/api/member/*"
    groups:
      enabled: true
  cache:
    disabled: true

