spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATA_URL}
    username: ${DATA_USERNAME}
    password: ${DATA_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      show-sql: true
      defer-datasource-initialization: true # data.sql 실행을 위한 추가


  sql:
    init:
      mode: always  # data.sql 실행을 위한 추가

jwt:
  secret: ahaahaahaackjbskjvbdjkbvwvkndfkvjbsdljnbcvwoieh

message:
  api:
    key: ${API_KEY}
    secret: ${API_SECRET}
  domain:
    address: https://api.coolsms.co.kr



